---
data-source:
  user: user
  password: user
  server: database
  port: 3306
  db: bike_blog
  charset: utf8
images:
  root: /var/bike-blog/img/
gps:
  root: /var/bike-blog/img/
  longitudeAndLatitudePrecision: 9
logs:
  root: /var/bike-blog/logs/
front-end:
  # Without / on the end
  apiBaseURl: ""
avocado:
  # PRODUCTION or DEVELOPMENT
  environment: DEVELOPMENT
  throws: false
