GET http://localhost/bike-blog/api/v1/news/
Accept: application/json

###
POST http://localhost/bike-blog/api/v1/news/
Content-Type: application/json

{
  "title": "Test",
  "description": "test",
  "tags": [
    "test",
    "Test2"
  ],
  "date": "2015-12-31"
}

###
GET http://localhost/bike-blog/api/v1/news/8aae5c3f-0e30-4196-b5db-34c36e249167

###
GET http://localhost/bike-blog/api/v1/news/tag/test12
